CREATE TABLE artifact (
	id SERIAL PRIMARY KEY,
	mime VARCHAR(255) NOT NULL,
	default_name VARCHAR(255) NOT NULL,
	source VARCHAR(255) NOT NULL,
	downloads INTEGER NOT NULL,
	created TIMESTAMP NOT NULL,
	expiry TIMESTAMP NULL,
	data BYTEA NOT NULL,
	dep_repo VARCHAR(255) NULL REFERENCES repo(id)
);

CREATE INDEX ON artifact(expiry);
