INSERT INTO `submit_rule`
VALUES (1, NULL, NULL, 0, 'About the plugin'),
       (2, NULL, NULL, 0, 'About the code'),
       (3, NULL, NULL, 0, 'About compatibility'),
       (4, NULL, NULL, 0, 'About the submit form'),
       (5, NULL, 1, 1,
        'These rules are about the idea of your plugin. Plugins with purpose violating these rules <strong>will never be approved</strong>.'),
       (6, NULL, 2, 1,
        'These rules are about the code in your plugin. If a plugin violates these rules, reviewers <strong>will reject the plugin</strong>, and you will have to change your code and submit the new build.'),
       (7, NULL, 3, 1,
        'These rules are here to make sure different plugins work well together. If a plugin violates these rules, reviewers <strong>will reject the plugin</strong>, and you will have to change your code and submit the new build.'),
       (8, NULL, 4, 1,
        'These rules are about the plugin submission form on Poggit. If a plugin violates these rules, reviewers <strong>will reset the plugin to draft</strong>, and the developer can edit the submission form and <strong>submit the same build again</strong>.'),
       (9, NULL, 1, 0, 'Complete and serve a purpose'),
       (10, NULL, 1, 0, 'Serve a <em>specific</em> purpose'),
       (11, NULL, 1, 0, 'No duplicates'),
       (12, NULL, 1, 0, 'Remote APIs'),
       (13, NULL, 1, 0, 'Payment must be optional'),
       (14, NULL, 1, 0, 'Libraries &amp; API plugins'),
       (15, NULL, 1, 0, 'Only submit your own plugins'),
       (16, NULL, 2, 0, 'No unused API versions'),
       (17, NULL, 2, 0, 'No obfuscated code'),
       (18, NULL, 2, 0, 'No eye-catching messages in startup/shutdown'),
       (19, NULL, 2, 0, 'Default must be English'),
       (20, NULL, 3, 0, 'Namespace format'),
       (21, NULL, 3, 0, 'Commands'),
       (22, NULL, 3, 0, 'Permissions'),
       (23, NULL, 3, 0, 'Events'),
       (24, NULL, 3, 0, 'Persisted data'),
       (25, NULL, 4, 0, 'Detailed description'),
       (26, NULL, 4, 0, 'The description must be available in English'),
       (27, NULL, 4, 0, 'Clean description'),
       (28, NULL, 4, 0, 'Beautiful description'),
       (29, NULL, 4, 0, 'Informative changelog'),
       (30, NULL, 4, 0, 'Pick a license carefully'),
       (41, NULL, 9, 1,
        'The plugin must be <strong>complete and serve a purpose</strong>. It is OK to have parts of the plugin not yet working, but they must be disabled by default. The other parts must serve a meaningful purpose.'),
       (42, NULL, 9, 1,
        'For example, it is reasonable to have a world editor plugin where only cuboid selection and setting blocks work, without support of spheres, copy/paste, etc. However, it is not reasonable to have a plugin where only cuboid selection works, because a plugin that only selects cuboids but does not do anything with it is completely useless.'),
       (43, NULL, 10, 1,
        'The plugin must <strong>serve a <em>specific</em> purpose</strong> and be useful to the majority of users.'),
       (44, NULL, 10, 1,
        '\"Core plugins\" are not accepted, because they are only useful on specific private servers.'),
       (45, NULL, 10, 1,
        'Plugins that contain many mutually irrelevant features are also not allowed, because they are a major source of bloatware (EssentialsPE and GrabBag are the only two exemptions due to their historical significance). Developers should strike a balance between too bloated and too simple, because both are undesirable for users.'),
       (46, NULL, 11, 1,
        'If there is another plugin that covers every single feature your plugin has, you must not submit yours, unless the existing one has been outdated and unmaintained for more than one month. You may want to explain why your plugin is better than the existing ones in the description.'),
       (47, NULL, 12, 1,
        'If the plugin requires an external API, it must either be from a reputable provider (e.g. Google APIs) or has high transparency. It must be clear that the plugin cannot be used as a backdoor for hacking servers. In particular, remote code execution is strictly prohibited. This includes auto-updaters from sources other than Poggit Release.'),
       (48, NULL, 13, 1,
        'The plugin must not impose limitations such that it is unusable without paying the developer. The plugin must at least be usable by a server with about 5 players online all-time. This is to make sure users have a chance to test your plugin without paying first.'),
       (49, NULL, 13, 1,
        'If the plugin uses an external API requires payment, it must have a reasonably usable free plan (e.g. a rate-limited free plan for ordinary small/medium-scale servers). It must also be transparent that paying will really do what is promised.'),
       (50, NULL, 14, 1,
        'Libraries must be included as <a href=\"https://poggit.pmmp.io/virion\">virions</a>. They must not be released as individual plugins.'),
       (51, NULL, 14, 1,
        'The <em>only</em> exception is when the plugin manages the compatibility among other plugins (a.k.a. API plugins). Rule 3 (no duplicates) is enforced more strictly regarding API plugins. API plugins must also have clear documentation for other plugin developers.'),
       (52, NULL, 15, 1, 'This rule is to be updated.'),
       (53, NULL, 16, 0, 'No unreleased API versions'),
       (54, NULL, 16, 0, 'No redundant API versions'),
       (55, NULL, 53, 1,
        'Plugins must not support <strong>unreleased</strong> API versions, i.e. anything not found in https://github.com/pmmp/PocketMine-MP/releases'),
       (56, NULL, 54, 1,
        'Plugins must not list <strong>redundant</strong> API versions in the plugin.yml. Only the earliest supported API in each major version needs to be listed, i.e. <code class=\"highlighter-rouge\">3.2.0</code> is not necessary if <code class=\"highlighter-rouge\">3.1.0</code> is already listed.'),
       (57, NULL, 17, 1,
        'The source code must be <strong>readable and not obfuscated</strong>. All PHP code can eventually be deobfuscated, so there is really no point of close-sourcing them.'),
       (58, NULL, 18, 1,
        'Colored messages, ASCII art, etc., are not allowed when the plugin is enabling/disabling under normal circumstances. This is explained in <a href=\"https://bit.ly/pmcolors\">https://bit.ly/pmcolors</a>.'),
       (59, NULL, 18, 1,
        'They are allowed if they represent actual warnings/errors or if they are responding to user input.'),
       (60, NULL, 18, 1,
        'Plugins must not log useless messages like \"I have been enabled\", unless the startup takes really a long time (more than 1 second) such that the user may become impatient.'),
       (61, NULL, 19, 1,
        'It is great if your plugin supports other languages, but since English is the most common languages that everyone knows, the default language must be set as English.'),
       (62, NULL, 20, 1,
        '<blockquote>TL;DR: change your plugin namespace to <code class=\"highlighter-rouge\">YourNamePluginName</code></blockquote>'),
       (63, NULL, 20, 0, 'Naming the namespace'),
       (64, NULL, 20, 0, 'Using the namespace'),
       (65, NULL, 20, 0, 'Changing the namespace'),
       (66, NULL, 63, 1,
        'All plugins must choose a <strong>unique namespace</strong> that will not be accidentally collided by other plugins. The plugin must begin with the author name (unless it is an official plugin, because the namespace <code class=\"highlighter-rouge\">pocketmine</code> is disallowed), followed by any identifier such that the author himself remembers which plugin it corresponds to. The recommended namespace format is <code class=\"highlighter-rouge\">AuthorNamePluginName</code>. The author name should use one that corresponds to the GitHub username/org name to prevent collision.'),
       (67, NULL, 64, 1,
        'All classes, interfaces and traits declared by plugins must be under this unique namespace (or subnamespaces). This includes libraries bundled with the plugin. Consider using the <a href=\"https://poggit.pmmp.io/virion\">virion framework</a>, which provides a convenient way of shading libraries (i.e. refactoring library classes into your plugin namespace).'),
       (68, NULL, 65, 1,
        'Plugin namespace should not change once it has been submitted unless there is an enormous API change that requires changing the namespace. But developers are recommended to obsolete the old version and submit a new plugin instead.'),
       (69, NULL, 21, 0, 'Command fallback prefix'),
       (70, NULL, 21, 0, 'Plugin-identifiable commands'),
       (71, NULL, 69, 1,
        'If the plugin registers commands by calling <code class=\"highlighter-rouge\">CommandMap-&gt;register</code> directly, the <code class=\"highlighter-rouge\">fallbackPrefix</code> parameter passed to the register function must be the plugin name. Plugins are not allowed to use its initials, acronyms, etc. for the fallback prefix.'),
       (72, NULL, 70, 1,
        'All commands must implement the <code class=\"highlighter-rouge\">PluginIdentifiableCommand</code> interface and return their plugin instance.'),
       (73, NULL, 22, 0, 'Permission name format'),
       (74, NULL, 73, 1,
        'If the plugin registers permissions, all permission names must start with the plugin name (does not need to contain the author name like the namespace). The permission name should only consist of alphabets, digits, hyphens and dots.'),
       (75, NULL, 23, 0, 'Use @ignoreCancelled and @priority'),
       (76, NULL, 23, 0, 'Do not change the event at <code>MONITOR</code> priority'),
       (77, NULL, 75, 1,
        'Event handlers should add the @ignoreCancelled tag if it does not expect to handle invalid events or events cancelled by other plugins.'),
       (78, NULL, 75, 1,
        'Event handlers should add the @priority to specify the event handling order. Handlers with smaller coverage (e.g. sign shop event handler) should use a lower priority (i.e. handled earlier), while handlers with larger coverage (e.g. area protection event handler) should use  a higher priority (i.e. handled later). Handlers that are only interested in the final outcome should use the MONITOR priority.'),
       (79, NULL, 76, 1,
        'No. Don\'t do that, even if you have technical difficulties and need to do so. Head out to our Discord to discuss for a better solution.'),
       (80, NULL, 24, 0, 'Stay in your data folder'),
       (81, NULL, 24, 0, 'Identify injected data by plugin namespace'),
       (82, NULL, 80, 1,
        'Except for plugin managers and plugins that affect how the server starts, do not create any files outside the designated <code>$this-&gt;getDataFolder()</code> directory. Do not assume that <code>chdir()</code> will only be used by your plugin. (Ideally, do not use <code>chdir</code> at all)'),
       (83, NULL, 81, 1,
        'If the plugin injects data to locations not managed by itself, the data must always be placed in a group identified by the plugin <strong>namespace</strong> (not just the plugin name). For example, if the plugin with namespace <code>SOFeSomePlugin</code> injects a custom NBT tag into an entity or an item, it must store its data under a compound tag called <code>SOFeSomePlugin</code>. (Aliases e.g. <code>SOFe.SomePlugin</code> are allowed as long as they can translate into the plugin namespace and be unique)'),
       (84, NULL, 25, 1,
        'The description should give an idea what the plugin is about, why it is useful, etc. Do not assume everyone knows the terminology; explain them.'),
       (85, NULL, 26, 1,
        'Translations are allowed, but English must be available first. We assume English as the language that most users know.'),
       (86, NULL, 27, 1,
        'Do not provide irrelevant information in the description. See <a href=\"/support/description-format.html\">description guide</a> for details. Do not advertise in the description. (Leaving a reasonable number of contacts is allowed)'),
       (87, NULL, 28, 1,
        'Format your description properly. The <a href=\"/support/description-formatting.html\">description formatting documentation</a> helps formatting according to Poggits special mechanisms like pagination.'),
       (88, NULL, 29, 1,
        'The changelog should be informative, in case the commit messages are not informative enough. The changelog should not contain meaningless lines like \"<code>Updated README.md</code>\".'),
       (89, NULL, 30, 1,
        'If you want to use a custom license, make sure it is formal enough. Examples of bad licenses include \"Everyone can use this plugin except leet.cc and @someone-I-hate</code>\".');
